version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./etc/dockerfiles/app.dockerfile
    working_dir: /src
    entrypoint: entrypoint
    volumes:
      - .:/src:delegated
      - /src/cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.facman.rule=Host(`facman.ginge.localhost`)"
    networks:
      - internal
      - local-mysql
      - traefik
    ports:
      - "8001:8000"

  node:
    build:
      context: .
      dockerfile: ./etc/dockerfiles/node.dockerfile
    working_dir: /src
    entrypoint: entrypoint
    volumes:
      - .:/src:delegated
      - /src/cache
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true
  local-mysql:
    external: true
